# Generated by Django 2.1.2 on 2018-12-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='man_hours',
        ),
        migrations.AddField(
            model_name='template',
            name='task_type',
            field=models.IntegerField(default=0),
        ),
    ]
