# Generated by Django 2.1.2 on 2018-12-23 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20181211_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('done', models.BooleanField(default=False)),
                ('staff', models.PositiveIntegerField(default=0)),
                ('days', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='task',
            name='department',
        ),
        migrations.RemoveField(
            model_name='task',
            name='done',
        ),
        migrations.AddField(
            model_name='subtask',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='quickstart.Department'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='quickstart.Task'),
        ),
    ]
