# Generated by Django 2.1.1 on 2018-12-23 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20181223_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTaskTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Подзадача', max_length=300)),
                ('days', models.PositiveIntegerField(default=0)),
                ('staff', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_templates', to='quickstart.Department')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задача', max_length=300)),
                ('task_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='template',
            name='department',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.AddField(
            model_name='subtasktemplate',
            name='task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubTaskTemplate', to='quickstart.TaskTemplate'),
        ),
    ]
