# Generated by Django 2.1.2 on 2018-12-24 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20181223_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subtasktemplate',
            name='task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_templates', to='quickstart.TaskTemplate'),
        ),
    ]
